color=18181b
font=JetBrains Mono
font-size=22

indicator-idle-visible
indicator-radius=100
indicator-thickness=8
indicator-caps-lock
show-failed-attempts

inside-color=18181bee
inside-clear-color=18181bee
inside-ver-color=18181bee
inside-wrong-color=18181bee
inside-caps-lock-color=18181bee

ring-color=89b4fa
ring-clear-color=f9e2af
ring-ver-color=a6e3a1
ring-wrong-color=f38ba8
ring-caps-lock-color=f9e2af

key-hl-color=cba6f7
bs-hl-color=f38ba8
caps-lock-key-hl-color=f9e2af
caps-lock-bs-hl-color=f38ba8

line-color=00000000
line-clear-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
line-caps-lock-color=00000000
separator-color=00000000

text-color=cdd6f4
text-clear-color=cdd6f4
text-ver-color=cdd6f4
text-wrong-color=f38ba8
text-caps-lock-color=f9e2af
